# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Form = QtWidgets.QLabel(self.centralwidget)
        self.Form.setGeometry(QtCore.QRect(275, 60, 150, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Form.setFont(font)
        self.Form.setAlignment(QtCore.Qt.AlignCenter)
        self.Form.setObjectName("Form")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 120, 120, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 190, 120, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.userLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.userLogin.setGeometry(QtCore.QRect(280, 120, 200, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.userLogin.setFont(font)
        self.userLogin.setObjectName("userLogin")
        self.passLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.passLogin.setGeometry(QtCore.QRect(280, 190, 200, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passLogin.setFont(font)
        self.passLogin.setObjectName("passLogin")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(330, 260, 150, 40))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuBeranda = QtWidgets.QMenu(self.menubar)
        self.menuBeranda.setObjectName("menuBeranda")
        self.menuLatihan = QtWidgets.QMenu(self.menubar)
        self.menuLatihan.setObjectName("menuLatihan")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeranda = QtWidgets.QAction(MainWindow)
        self.actionBeranda.setObjectName("actionBeranda")
        self.actionLatihan = QtWidgets.QAction(MainWindow)
        self.actionLatihan.setObjectName("actionLatihan")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSurat = QtWidgets.QAction(MainWindow)
        self.actionSurat.setObjectName("actionSurat")
        self.menuBeranda.addAction(self.actionBeranda)
        self.menuLatihan.addAction(self.actionLatihan)
        self.menuAdmin.addAction(self.actionLogin)
        self.menubar.addAction(self.menuBeranda.menuAction())
        self.menubar.addAction(self.menuLatihan.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Form.setText(_translate("MainWindow", "Login Admin"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.menuBeranda.setTitle(_translate("MainWindow", "Beranda"))
        self.menuLatihan.setTitle(_translate("MainWindow", "Latihan"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.actionBeranda.setText(_translate("MainWindow", "Beranda"))
        self.actionLatihan.setText(_translate("MainWindow", "Latihan"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionSurat.setText(_translate("MainWindow", "Surat"))
