# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataLatih.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabelLatih = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelLatih.setGeometry(QtCore.QRect(30, 80, 571, 291))
        self.tabelLatih.setObjectName("tabelLatih")
        self.tabelLatih.setColumnCount(3)
        self.tabelLatih.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelLatih.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelLatih.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelLatih.setHorizontalHeaderItem(2, item)
        self.btnPutarLatih = QtWidgets.QPushButton(self.centralwidget)
        self.btnPutarLatih.setGeometry(QtCore.QRect(620, 100, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPutarLatih.setFont(font)
        self.btnPutarLatih.setObjectName("btnPutarLatih")
        self.btnUbahLatih = QtWidgets.QPushButton(self.centralwidget)
        self.btnUbahLatih.setGeometry(QtCore.QRect(620, 170, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnUbahLatih.setFont(font)
        self.btnUbahLatih.setObjectName("btnUbahLatih")
        self.btnTambahLatih = QtWidgets.QPushButton(self.centralwidget)
        self.btnTambahLatih.setGeometry(QtCore.QRect(620, 240, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnTambahLatih.setFont(font)
        self.btnTambahLatih.setObjectName("btnTambahLatih")
        self.btnHapusLatih = QtWidgets.QPushButton(self.centralwidget)
        self.btnHapusLatih.setGeometry(QtCore.QRect(620, 310, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnHapusLatih.setFont(font)
        self.btnHapusLatih.setObjectName("btnHapusLatih")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data Latih"))
        item = self.tabelLatih.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.tabelLatih.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tajwid"))
        item = self.tabelLatih.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Path"))
        self.btnPutarLatih.setText(_translate("MainWindow", "Putar"))
        self.btnUbahLatih.setText(_translate("MainWindow", "Ubah"))
        self.btnTambahLatih.setText(_translate("MainWindow", "Tambah"))
        self.btnHapusLatih.setText(_translate("MainWindow", "Hapus"))
