# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TambahAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 40, 150, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 120, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 120, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 120, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lblUserTambah = QtWidgets.QLineEdit(self.centralwidget)
        self.lblUserTambah.setGeometry(QtCore.QRect(170, 100, 200, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblUserTambah.setFont(font)
        self.lblUserTambah.setObjectName("lblUserTambah")
        self.lblPassTambah = QtWidgets.QLineEdit(self.centralwidget)
        self.lblPassTambah.setGeometry(QtCore.QRect(170, 150, 200, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassTambah.setFont(font)
        self.lblPassTambah.setObjectName("lblPassTambah")
        self.lblRepassTambah = QtWidgets.QLineEdit(self.centralwidget)
        self.lblRepassTambah.setGeometry(QtCore.QRect(170, 200, 200, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblRepassTambah.setFont(font)
        self.lblRepassTambah.setObjectName("lblRepassTambah")
        self.btnBuatAdmin = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuatAdmin.setGeometry(QtCore.QRect(270, 260, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnBuatAdmin.setFont(font)
        self.btnBuatAdmin.setObjectName("btnBuatAdmin")
        self.btnKembali = QtWidgets.QPushButton(self.centralwidget)
        self.btnKembali.setGeometry(QtCore.QRect(170, 260, 100, 30))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnKembali.setFont(font)
        self.btnKembali.setObjectName("btnKembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tambah Admin"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Re-Password"))
        self.btnBuatAdmin.setText(_translate("MainWindow", "Buat"))
        self.btnKembali.setText(_translate("MainWindow", "Kembali"))
